version: '3.4'

services:
  jordiaragonzaragoza.todos:
    image: ${DOCKER_REGISTRY-}jordiaragonzaragoza.todos
    container_name: jordiaragonzaragoza.todos
    build:
      context: .
      dockerfile: services/JordiAragonZaragoza.ToDos/src/JordiAragonZaragoza.ToDos/Dockerfile

  jordiaragonzaragoza.messagehub:
    image: ${DOCKER_REGISTRY-}jordiaragonzaragoza.messagehub
    container_name: jordiaragonzaragoza.messagehub
    build:
      context: .
      dockerfile: services/JordiAragonZaragoza.MessageHub/src/JordiAragonZaragoza.MessageHub/Dockerfile

  azuresqledge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: azuresqledge

  rabbitmq:
    image: rabbitmq:3.11.10-management
    container_name: rabbitmq
    hostname: rabbitmq